### ISSUE TITLE
How did you generate the legacy code?

### ISSUE THREAD

**Issue by prabak** [mehamasum/pxt-blockly-static-demo#1]
Hi,

how did you generate the legacy code (*_v0) and the non-legacy code? I am trying to figure out where the legacy code came from? I am assuming the non-legacy code is obtained from pxt-blockly. 

thank you

**Comment by mehamasum** [comment]
Both of them be can be generated from the Github repo of Microsoft's PXT Blockly while the legacy code is in the v0 branch and non legacy is in master.

**Comment by prabak** [comment]
thanks
